In [3]:
import pandas as pd

In [4]:
jan = pd.read_excel("January.xlsx")
feb = pd.read_excel("February.xlsx")
mar = pd.read_excel("March.xlsx")
apr = pd.read_excel("April.xlsx")
may = pd.read_excel("May.xlsx")
jun = pd.read_excel("June.xlsx")
jul = pd.read_excel("July.xlsx")
aug = pd.read_excel("August.xlsx")
sept = pd.read_excel("September.xlsx")
oct = pd.read_excel("October.xlsx")
nov = pd.read_excel("November.xlsx")
dec = pd.read_excel("December.xlsx")

In [5]:
jan

         Date Invoice_No Customer   Product  Quantity  Sales
0  2026-01-01    JAN-001    Rahul    Laptop         1   5100
1  2026-01-02    JAN-002      Anu     Mouse         2  10100
2  2026-01-03    JAN-003     Arun  Keyboard         3  15100
3  2026-01-04    JAN-004    Meena   Monitor         4  20100
4  2026-01-05    JAN-005    Priya   Printer         5  25100

In [6]:
feb

         Date Invoice_No Customer   Product  Quantity  Sales
0  2026-02-01    FEB-001    Rahul    Laptop         1   5200
1  2026-02-02    FEB-002      Anu     Mouse         2  10200
2  2026-02-03    FEB-003     Arun  Keyboard         3  15200
3  2026-02-04    FEB-004    Meena   Monitor         4  20200
4  2026-02-05    FEB-005    Priya   Printer         5  25200

In [7]:
mar

         Date Invoice_No Customer   Product  Quantity  Sales
0  2026-03-01    MAR-001    Rahul    Laptop         1   5300
1  2026-03-02    MAR-002      Anu     Mouse         2  10300
2  2026-03-03    MAR-003     Arun  Keyboard         3  15300
3  2026-03-04    MAR-004    Meena   Monitor         4  20300
4  2026-03-05    MAR-005    Priya   Printer         5  25300

In [8]:
apr

         Date Invoice_No Customer   Product  Quantity  Sales
0  2026-04-01    APR-001    Rahul    Laptop         1   5400
1  2026-04-02    APR-002      Anu     Mouse         2  10400
2  2026-04-03    APR-003     Arun  Keyboard         3  15400
3  2026-04-04    APR-004    Meena   Monitor         4  20400
4  2026-04-05    APR-005    Priya   Printer         5  25400

In [9]:
may

         Date Invoice_No Customer   Product  Quantity  Sales
0  2026-05-01    MAY-001    Rahul    Laptop         1   5500
1  2026-05-02    MAY-002      Anu     Mouse         2  10500
2  2026-05-03    MAY-003     Arun  Keyboard         3  15500
3  2026-05-04    MAY-004    Meena   Monitor         4  20500
4  2026-05-05    MAY-005    Priya   Printer         5  25500

In [10]:
jun

         Date Invoice_No Customer   Product  Quantity  Sales
0  2026-06-01    JUN-001    Rahul    Laptop         1   5600
1  2026-06-02    JUN-002      Anu     Mouse         2  10600
2  2026-06-03    JUN-003     Arun  Keyboard         3  15600
3  2026-06-04    JUN-004    Meena   Monitor         4  20600
4  2026-06-05    JUN-005    Priya   Printer         5  25600

In [11]:
jul

         Date Invoice_No Customer   Product  Quantity  Sales
0  2026-07-01    JUL-001    Rahul    Laptop         1   5700
1  2026-07-02    JUL-002      Anu     Mouse         2  10700
2  2026-07-03    JUL-003     Arun  Keyboard         3  15700
3  2026-07-04    JUL-004    Meena   Monitor         4  20700
4  2026-07-05    JUL-005    Priya   Printer         5  25700

In [13]:
aug

         Date Invoice_No Customer   Product  Quantity  Sales
0  2026-08-01    AUG-001    Rahul    Laptop         1   5800
1  2026-08-02    AUG-002      Anu     Mouse         2  10800
2  2026-08-03    AUG-003     Arun  Keyboard         3  15800
3  2026-08-04    AUG-004    Meena   Monitor         4  20800
4  2026-08-05    AUG-005    Priya   Printer         5  25800

In [15]:
sept

         Date Invoice_No Customer   Product  Quantity  Sales
0  2026-09-01    SEP-001    Rahul    Laptop         1   5900
1  2026-09-02    SEP-002      Anu     Mouse         2  10900
2  2026-09-03    SEP-003     Arun  Keyboard         3  15900
3  2026-09-04    SEP-004    Meena   Monitor         4  20900
4  2026-09-05    SEP-005    Priya   Printer         5  25900

In [16]:
oct

         Date Invoice_No Customer   Product  Quantity  Sales
0  2026-10-01    OCT-001    Rahul    Laptop         1   6000
1  2026-10-02    OCT-002      Anu     Mouse         2  11000
2  2026-10-03    OCT-003     Arun  Keyboard         3  16000
3  2026-10-04    OCT-004    Meena   Monitor         4  21000
4  2026-10-05    OCT-005    Priya   Printer         5  26000

In [17]:
nov

         Date Invoice_No Customer   Product  Quantity  Sales
0  2026-11-01    NOV-001    Rahul    Laptop         1   6100
1  2026-11-02    NOV-002      Anu     Mouse         2  11100
2  2026-11-03    NOV-003     Arun  Keyboard         3  16100
3  2026-11-04    NOV-004    Meena   Monitor         4  21100
4  2026-11-05    NOV-005    Priya   Printer         5  26100

In [18]:
dec

         Date Invoice_No Customer   Product  Quantity  Sales
0  2026-12-01    DEC-001    Rahul    Laptop         1   6200
1  2026-12-02    DEC-002      Anu     Mouse         2  11200
2  2026-12-03    DEC-003     Arun  Keyboard         3  16200
3  2026-12-04    DEC-004    Meena   Monitor         4  21200
4  2026-12-05    DEC-005    Priya   Printer         5  26200

In [20]:
master=pd.concat([
    jan, feb, mar, apr, may, jun, jul, aug, sept, oct, nov, dec
])
master.to_excel("Master_Sales_mithun.xlsx", index=False)
print("All 12 month merged successfully")

All 12 month merged successfully

In [21]:
year=pd.read_excel("Master_Sales_mithun.xlsx")

In [22]:
year

          Date Invoice_No Customer   Product  Quantity  Sales
0   2026-01-01    JAN-001    Rahul    Laptop         1   5100
1   2026-01-02    JAN-002      Anu     Mouse         2  10100
2   2026-01-03    JAN-003     Arun  Keyboard         3  15100
3   2026-01-04    JAN-004    Meena   Monitor         4  20100
4   2026-01-05    JAN-005    Priya   Printer         5  25100
5   2026-02-01    FEB-001    Rahul    Laptop         1   5200
6   2026-02-02    FEB-002      Anu     Mouse         2  10200
7   2026-02-03    FEB-003     Arun  Keyboard         3  15200
8   2026-02-04    FEB-004    Meena   Monitor         4  20200
9   2026-02-05    FEB-005    Priya   Printer         5  25200
10  2026-03-01    MAR-001    Rahul    Laptop         1   5300
11  2026-03-02    MAR-002      Anu     Mouse         2  10300
12  2026-03-03    MAR-003     Arun  Keyboard         3  15300
13  2026-03-04    MAR-004    Meena   Monitor         4  20300
14  2026-03-05    MAR-005    Priya   Printer         5  25300
15  2026-04-01    APR-001    Rahul    Laptop         1   5400
16  2026-04-02    APR-002      Anu     Mouse         2  10400
17  2026-04-03    APR-003     Arun  Keyboard         3  15400
18  2026-04-04    APR-004    Meena   Monitor         4  20400
19  2026-04-05    APR-005    Priya   Printer         5  25400
20  2026-05-01    MAY-001    Rahul    Laptop         1   5500
21  2026-05-02    MAY-002      Anu     Mouse         2  10500
22  2026-05-03    MAY-003     Arun  Keyboard         3  15500
23  2026-05-04    MAY-004    Meena   Monitor         4  20500
24  2026-05-05    MAY-005    Priya   Printer         5  25500
25  2026-06-01    JUN-001    Rahul    Laptop         1   5600
26  2026-06-02    JUN-002      Anu     Mouse         2  10600
27  2026-06-03    JUN-003     Arun  Keyboard         3  15600
28  2026-06-04    JUN-004    Meena   Monitor         4  20600
29  2026-06-05    JUN-005    Priya   Printer         5  25600
30  2026-07-01    JUL-001    Rahul    Laptop         1   5700
31  2026-07-02    JUL-002      Anu     Mouse         2  10700
32  2026-07-03    JUL-003     Arun  Keyboard         3  15700
33  2026-07-04    JUL-004    Meena   Monitor         4  20700
34  2026-07-05    JUL-005    Priya   Printer         5  25700
35  2026-08-01    AUG-001    Rahul    Laptop         1   5800
36  2026-08-02    AUG-002      Anu     Mouse         2  10800
37  2026-08-03    AUG-003     Arun  Keyboard         3  15800
38  2026-08-04    AUG-004    Meena   Monitor         4  20800
39  2026-08-05    AUG-005    Priya   Printer         5  25800
40  2026-09-01    SEP-001    Rahul    Laptop         1   5900
41  2026-09-02    SEP-002      Anu     Mouse         2  10900
42  2026-09-03    SEP-003     Arun  Keyboard         3  15900
43  2026-09-04    SEP-004    Meena   Monitor         4  20900
44  2026-09-05    SEP-005    Priya   Printer         5  25900
45  2026-10-01    OCT-001    Rahul    Laptop         1   6000
46  2026-10-02    OCT-002      Anu     Mouse         2  11000
47  2026-10-03    OCT-003     Arun  Keyboard         3  16000
48  2026-10-04    OCT-004    Meena   Monitor         4  21000
49  2026-10-05    OCT-005    Priya   Printer         5  26000
50  2026-11-01    NOV-001    Rahul    Laptop         1   6100
51  2026-11-02    NOV-002      Anu     Mouse         2  11100
52  2026-11-03    NOV-003     Arun  Keyboard         3  16100
53  2026-11-04    NOV-004    Meena   Monitor         4  21100
54  2026-11-05    NOV-005    Priya   Printer         5  26100
55  2026-12-01    DEC-001    Rahul    Laptop         1   6200
56  2026-12-02    DEC-002      Anu     Mouse         2  11200
57  2026-12-03    DEC-003     Arun  Keyboard         3  16200
58  2026-12-04    DEC-004    Meena   Monitor         4  21200
59  2026-12-05    DEC-005    Priya   Printer         5  26200